version: '3.9'

services:
  web:
    build: 
      context: .
    command: >
      bash -c "
        export PYTHONPATH=/app &&
        python -m app.db.setup_db &&
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./app:/app/app
      - whisper_models:/app/models
      - whisper_cache:/app/.cache/whisper
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medicai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=medicai
      - WHISPER_MODELS_DIR=/app/models
      - WHISPER_MODEL_SIZE=base
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    dns_search:
      - medicai-network
    extra_hosts:
      - "files.pythonhosted.org:151.101.128.223"
      - "pypi.org:151.101.128.223"
      - "pypi.python.org:151.101.128.223"
    networks:
      - medicai-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medicai
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search:
      - medicai-network
    networks:
      - medicai-network

  frontend:
    build: 
      context: ./frontend
      args:
        - NODE_ENV=production
        - NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_OPTIONS="--max-old-space-size=4096"
    depends_on:
      web:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search:
      - medicai-network
    networks:
      - medicai-network

volumes:
  postgres_data:
  whisper_models:
  whisper_cache:

networks:
  medicai-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"